name: Ansible Tower Job Success

on:
  push:
    branches: [ "main" ]
  repository_dispatch:
    types: [ansible_tower_success]
  workflow_dispatch: 

jobs:
  run_on_success:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Webhook Token (Optional but Recommended)
        run: ls

      - name: Print Hello World (Example Action)
        run: |
          echo "Received event payload:"
          echo "${{ github.event.client_payload }}"
          echo "Hello, world! Ansible Tower job succeeded!"
