name: My Test Workflow

# on:
#   workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a simple command
        run: echo "Hello from GitHub Actions!"
