name: My Test Workflow
on:
  workflow_dispatch:
  push:
    branches:
    - main
  
jobs:
  my-job:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code in GitHub action
        uses: actions/checkout@v3

      - name: Run Echo commands in Logs
        run: echo "build since workflows were changed"
